### ISSUE TITLE
Feature Request: Update initial comment with vote info

### ISSUE THREAD

**Issue by jeefy** [cncf/gitvote#162]
Per @richih's comment in https://github.com/cncf/sandbox/pull/14#issuecomment-1330765976

It'd be nice if the initial comment was updated with binding votes (as they happen) _as well as_ the Timestamp that the vote occurred.

**Comment by tegioz** [comment]
Hi @jeefy @RichiH 👋 

GitVote subscribes to certain events in GitHub to process votes. AFAIK there is no event for reactions in comments at the moment (I'll double check), so I think we wouldn't be able to update the comment *as votes happen*. We could poll the comment periodically to get the reactions though, but this may get tricky as well: doing it too often may lead to GitHub API rate limit issues, and doing it every now and then may be annoying as the votes displayed may not match with the reactions (changed votes, new votes not picked up yet, etc).

We've tried to minimize the interactions with the GH API as much as possible, so GitVote doesn't do much on a given vote since the moment it is created until it's time to close it. When the time comes, we collect all the info we need to compute the results, display them via a new comment and close the vote. The goal was to make it as light as possible as eventually there could be a lot of votes in progress (specially if the app is publicly available at some point).

The timestamp is a very good point, thanks! We could display it when the vote is closed, next to the handle of each of the voters. We'll take care of this 🙂

**Comment by RichiH** [comment]
If you do not get events from the GitHub API, how will you implement timestamps?

Do you know what API limits you are likely to hit? Would polling every minute or five minutes be too often?

**Comment by tegioz** [comment]
> If you do not get events from the GitHub API, how will you implement timestamps?

The timestamp is part of the information we get when fetching all the reactions on a given comment (along with the user, the reaction content, etc).

> Do you know what API limits you are likely to hit? Would polling every minute or five minutes be too often?

The default limit is 5000 requests/hour (can get higher if the organization is large or when using GitHub Enterprise).

That would mean that if this feature was the only API user, we could only have ~80 open votes on a given organization if we were polling every 1m (or ~400 if we were polling every 5m). But there are other operations that require multiple API calls (creating votes, closing, etc), so this number would be lower. There are also other secondary rate limits we've reached in other apps that are not as clearly documented (they depend on how fast you hit them, concurrency, etc). And reaching any of those limits could affect core operations like creating a new vote or closing a finished one.

IMHO it feels a bit limiting for a feature that's not critical, as that information is already available by taking a look at the reactions. Polling every 5m would also mean that there would be periods of time when the reactions as displayed on the comment would not match our results, giving the impression that something is broken.

We'll double check if there is already an event we can subscribe to for reactions in comments. If it's not available yet, we can always revisit this feature when it is at some point 🙂

**Comment by RichiH** [comment]
Yes, this sounds reasonable, thank you.

It might be worth asking GH for a new event to subscribe to; or to poll every hour and update very lazily.

**Comment by tegioz** [comment]
No worries, thanks! 👍

**Comment by RichiH** [comment]
After the current round of voting, having the results at the end of thread, not in the initial vote starting comment, is confusing and arguably spammy; see e.g. https://github.com/cncf/sandbox/issues/12

Editing the initial comment, not adding new ones, would likely be better.

**Comment by tegioz** [comment]
Thanks @RichiH 👍

IMHO this could be a matter of preference, as some users may find useful getting notified when a new vote status is posted, or when it is closed. It can also be of help as a reminder in some cases.

Anyway, let's see what others think about this 🙂

We need to keep in mind that the GitVote GitHub application is now publicly available. Some organizations are considering to use it and usage will probably grow over time. My point is that we need to be aware that important user facing changes may end up confusing users (i.e. they may expect a new comment with the results that will never be posted). So the more consensus and feedback we can get, the better.

**Comment by RichiH** [comment]
@tegioz With the limited feedback we're getting here, I see a clear preference for the behavior I proposed. If in doubt, making it configurable would be an option.

**Comment by amye** [comment]
So one thing that we need to keep in mind is a need for an audit trail. 
Having the comment at the end assures both when the votes happen AND the result, we need to keep that.

**Comment by tegioz** [comment]
> After the current round of voting, having the results at the end of thread, not in the initial vote starting comment, is confusing and arguably spammy.

Will close this issue for now because, as @amye explained, having both the initial vote comment and the one with the results at the end is helpful for auditing purposes. But feel free to reopen if needed 🙂

**Comment by tegioz** [comment]
> Now I'll have to spam `/check-vote` for [cncf/toc#925](https://github.com/cncf/toc/pull/925) which is noisy

Hi @tomkerkhove 👋

We'll add soon a new feature to [auto-close a vote when the vote passes](https://github.com/cncf/gitvote/issues/335) that hopefully will help with this too 🙂

**Comment by tomkerkhove** [comment]
But that is different though, if the vote takes 30 days we won't get any insights until everything completed which is very bad imo.

Today we will have to poke the issue to dump voting status every x days, just to know how things are going.

**Comment by tegioz** [comment]
> But that is different though, if the vote takes 30 days we won't get any insights until everything completed which is very bad imo. Today we will have to poke the issue to dump voting status every x days, just to know how things are going.

I meant that at least you wouldn't need to check often if the vote has passed because you'll be notified as soon as it does.

Regarding asking the bot periodically, GitVote has a [feature to check votes automatically at a configured frequency](https://github.com/cncf/gitvote/blob/fc2ca3bbb27bf49f216f718cd490da3dddb4d3d8/docs/config/.gitvote.yml#L97-L124), but it hasn't been enabled yet on the TOC repo. For votes that may last long, maybe we could set it up to check automatically every week, for example.

**Comment by tegioz** [comment]
> Another approach is to post a comment about vote starting which is not updated followed by a new comment that represents the current state. Once the vote is complete, a 3rd comment is posted and issue closed.

We are actually considering this approach, we discussed it recently. But we still need to see how it fits with the rest of the features (like asking the bot manually to check a vote, as results would be posted on that comment instead of after the /check-vote one, which could be confusing -and some /check-vote comments could pile up-). Also there would be no trace of the vote status at each of those points in time. We may end up enabling the periodic auto-check for all votes in combination with this eventually, but it still needs a bit more thinking.

Thanks for the feedback! We are restricted by the options we have inside GitHub, which mainly would be asking voters to post a comment in certain format (i.e. +1, but this would be really noisy too, like a mailing list), or using reactions. But we'll try to keep improving the experience 🙂

**Comment by tomkerkhove** [comment]
> Regarding asking the bot periodically, GitVote has a [feature to check votes automatically at a configured frequency](https://github.com/cncf/gitvote/blob/fc2ca3bbb27bf49f216f718cd490da3dddb4d3d8/docs/config/.gitvote.yml#L97-L124), but it hasn't been enabled yet on the TOC repo. For votes that may last long, maybe we could set it up to check automatically every week, for example.

This is actually what is missing today, thanks for bringing this up! Created https://github.com/cncf/toc/pull/1107 so let's see if it gets accepted.



> > Another approach is to post a comment about vote starting which is not updated followed by a new comment that represents the current state. Once the vote is complete, a 3rd comment is posted and issue closed.
> 
> We are actually considering this approach, we discussed it recently. But we still need to see how it fits with the rest of the features (like asking the bot manually to check a vote, as results would be posted on that comment instead of after the /check-vote one, which could be confusing -and some /check-vote comments could pile up-). Also there would be no trace of the vote status at each of those points in time. We may end up enabling the periodic auto-check for all votes in combination with this eventually, but it still needs a bit more thinking.
> 
> Thanks for the feedback! We are restricted by the options we have inside GitHub, which mainly would be asking voters to post a comment in certain format (i.e. +1, but this would be really noisy too, like a mailing list), or using reactions. But we'll try to keep improving the experience 🙂

That makes sense, thanks for sharing! Let's see if the additional comment is feasible indeed.

**Comment by RichiH** [comment]
GitHub allows you to see edited comments, so there is an audit trail in
edits as well.

The audit trail could also be persisted outside of the comments, e.g. in a
distinct repository.

Put differently: While I understand and agree with audit requirements, the
current UX of the vote tooling is far from ideal. It's hard to get a quick
overview and is extremely spammy. Splitting audit trail from main UI seems
reasonable to me.

Sent by mobile; please excuse my brevity.
