### ISSUE TITLE
Feature Request: View Non-Binding Votes

### ISSUE THREAD

**Issue by jeefy** [cncf/gitvote#171]
Once a vote concludes, it would be nice if there was an (expandable) table that showed all non-binding votes. 

That table might be large, so again, I'm thinking it's expandable. Collapsed it would just display something like "Total Non-Binding Votes: (100)"

Thoughts? 

cc @caniszczyk @amye

**Comment by amye** [comment]
That sounds fine!

**Comment by tegioz** [comment]
I think the maximum number of characters in a comment body in GitHub is ~65k, which with the current information we display could be enough for less that 1000 votes. Maybe we could display a maximum of a few hundred (maybe 300 or 500?), to make sure that limit is never reached (otherwise trying to publish the vote closed comment would fail).

**Comment by tegioz** [comment]
This is ready @jeefy 🙂

For now we are only displaying the first 300 non-binding votes (we display a message when that limit is reached), but we can tweak that number if needed.

<img width="927" alt="non-binding" src="https://user-images.githubusercontent.com/1213902/206709886-5a554270-8bf3-4430-bdbb-ebd4508b1e76.png">
